imports:
    - { resource: config.yml }

as3_modlr:
    persisters:
        default:
            type: mongodb
            parameters:
                host: mongodb://mongo.platform.baseplatform.io:27017
                options:
                    readPreference: nearest
                    replicaSet: platform
                    journal: true
                    connectTimeoutMS: 200
                    w: ~

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        console:
            type: console
            process_psr_3_messages: false
